name: Build

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    runs-on: ubuntu-22.04

    env:
      RUSTFLAGS: "--deny warnings"

    defaults:
      run:
        working-directory: tests

    steps:
    - uses: actions/checkout@v4

    # Vim maybe already installed, but this appears to be an undocumented implementation detail.
    # Make sure Vim is installed and working, and log Vim version.
    - name: Vim
      run: |
        if ! which vim ;then
          sudo apt-get update
          sudo apt-get -y install vim
        fi
        vim --version

    - name: Download Neovim
      run: gh -R neovim/neovim release download -p nvim-linux64.tar.gz
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Neovim
      run: |
        tar -C "$HOME" -xaf nvim-linux64.tar.gz
        "$HOME/nvim-linux64/bin/nvim" --version

    - name: Rust Toolchain Info
      run: |
        rustc --version
        cargo --version
        cargo clippy --version
        cargo fmt --version

    - uses: Swatinem/rust-cache@640a22190e7a783d4c409684cea558f081f92012
      with:
        workspaces: ./tests -> target

    - name: Build
      run: cargo build --workspace

    - name: Clippy
      run: cargo clippy --all-targets --all-features

    - name: Check Formatting
      run: cargo fmt --all --check

    - name: Test Vim
      run: |
        cargo run
        cargo run --bin=test-ftdetect

    - name: Test Neovim
      run: |
        export TEST_VIM="$HOME/nvim-linux64/bin/nvim"
        cargo run
        cargo run --bin=test-ftdetect
