name: Build

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "--deny warnings"

    defaults:
      run:
        working-directory: tests

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ hashFiles('**/src/main.rs') }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust Toolchain Components
      run: |
        rustup component add clippy rustfmt

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install colordiff ripgrep

    - name: Info
      run: |
        rustup --version
        cargo --version
        cargo clippy --version
        cargo fmt --version

    - name: Build
      run: cargo build --workspace

    - name: Clippy
      run: cargo clippy --all-targets --all-features

    - name: Check Formatting
      run: cargo fmt --all -- --check

    - name: Check for Forbidden Words
      run: ./bin/forbid

    - name: Test
      run: |
        cargo run
        cargo run --bin=test-ftdetect
