name: Build

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  all:
    name: All

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "--deny warnings"

    defaults:
      run:
        working-directory: tests

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Toolchain Components
      run: |
        rustup component add clippy rustfmt

    - name: Info
      run: |
        rustup --version
        cargo --version
        cargo clippy --version
        cargo fmt --version

    - uses: Swatinem/rust-cache@378c8285a4eaf12899d11bea686a763e906956af
      with:
        workspaces: ./tests -> target

    - name: Build
      run: cargo build --workspace

    - name: Clippy
      run: cargo clippy --all-targets --all-features

    - name: Check Formatting
      run: cargo fmt --all -- --check

    - name: Test
      run: |
        cargo run
        cargo run --bin=test-ftdetect
